name: mpt_2022

dependencies:
  - python=3.9
  - pip
  - conda-build
  - pytest
  - ffmpeg
  - numpy
  - pandas
  - matplotlib
  - ipykernel
  # medleydb requirements
  - pyyaml=5.4.1
  - scikit-learn >= 0.1
  - pip:
    - librosa==0.9.2
    - sox>=1.2.3
